gourmet_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gsapp.urls")),
]

gsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "gsapp"
urlpatterns = [
    path("", views.IndexView.as_view(), name = "index"),
    path("search/", views.SearchView.as_view(), name = "search"),
    path("gourmet_list/", views.gourmet_list, name = "gourmet_list"),
    path("detail/<str:id>/", views.detail_view, name = "detail"),
]

gsapp/models.py
from django.db import models

# Create your models here.

gsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views import generic
import requests
import os
from datetime import datetime
from django_user_agents.utils import get_user_agent

class IndexView(generic.TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        api_endpoint = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
        api_key = os.environ.get("API_KEY")

        context = super().get_context_data(**kwargs)

        params = {
            "key": api_key,
            "keyword": "インスタ映え",
            "count": 50,
            "format":"json",
        }
        response = requests.get(api_endpoint, params=params)


        if response.status_code == 200:
            data = response.json()

            gourmet_photo = data["results"]["shop"]

            context["gourmet_photo"] = gourmet_photo

            is_mobile = get_user_agent(self.request).is_mobile
            context["is_mobile"] = is_mobile

            return context
        
        else:
            # エラーメッセージを表示
            pass

        

class SearchView(generic.TemplateView):
    template_name = "search.html"


def gourmet_list(request):

    api_endpoint = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
    api_key = os.environ.get("API_KEY")

    genre = request.GET.get("genre", "")
    budget = request.GET.get("budget", "")
    range = request.GET.get("range", "")
    lat = request.GET.get("lat", "")
    lng = request.GET.get("lng", "")


    params = {
        "key": api_key,
        "genre": genre,
        "budget": budget,
        "count": 60,
        "lat": lat,
        "lng": lng,
        "range": range,
        "format":"json",
    }



    response = requests.get(api_endpoint, params=params)


    if response.status_code == 200:
        data = response.json()

        gourmet_list = data["results"]["shop"]

        per_page = 10
        page_num = request.GET.get("page", 1)
        paginator = Paginator(gourmet_list, per_page)
        page_obj = paginator.get_page(page_num)

        is_mobile = get_user_agent(request).is_mobile

        context = {
            "page_obj": page_obj,
            "is_mobile": is_mobile,
        }

        return render(request, "gourmet_list.html", context)
    else:
        # エラーメッセージを表示
        pass


def detail_view(request, id):

    api_endpoint = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
    api_key = "1b1c0aede467a3f4"


    params = {
        "key": api_key,
        "id": id,
        "format":"json",
    }

    response = requests.get(api_endpoint, params=params)
    if response.status_code == 200:
        data = response.json()

        gourmet_detail = data["results"]["shop"][0]

        current_time = datetime.now().time()
        is_mobile = get_user_agent(request).is_mobile

        print(gourmet_detail)


        context = {
            "detail": gourmet_detail,
            "current_time": current_time,
            "is_mobile": is_mobile,
        }

        return render(request, "detail.html", context)
    else:
        pass

gsapp/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang = "ja">
    <head>
        <meta charset = "UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}{% endblock %}</title>
        <link rel = "stylesheet" href = "{%static 'css/common.css'%}">
        {%block head%}{%endblock%}
    </head>

    <body>
        <header>
            {% block logo %}{% endblock logo %}
        </header>
        {%block content%}{%endblock%}
        <footer>
        </footer>
        {% block js %}{% endblock js %}
    </body>
</html>

gsapp/templates/detail.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel = "stylesheet" href = "{%static 'css/detail.css'%}">
{% endblock head %}

{% block title %}モグマッチ｜店舗詳細{% endblock title %}

{% block logo %}
<a href="{% url 'gsapp:index' %}" class="logo-container"><img src="{% static 'images/logo_orange.svg' %}" alt="モグマッチ" id = "logo"></a>
{% endblock logo %}

{% block content %}
<div class="background"></div>
<div class="content">
    <a href="#" onclick="history.back()"; return="false"; class="btn-back">&lsaquo;</a>
    <h2>検索結果</h2>
    <hr>
    <div class="detail">
        <div class="detail-info">
            <h2 class="name">{{ detail.name }}</h2>
            <p><span class="bold">ジャンル：</span>{{detail.genre.name}}・{{ detail.genre.catch }}</p>
            <p><span class = "bold">所在地：</span> {{ detail.address }}</p>
            <p><span class="bold">営業時間： </span>{{ detail.open }}</p>
            {% if detail.budget.average %}
            <p><span class = "bold">平均予算：</span> {{ detail.budget.average }}</p>
            {% else %}
            <p><span class = "bold">平均予算：</span> 不明</p>
            {% endif %}

            {% if is_mobile %}
            <img src="{{ detail.photo.mobile.l }}" alt="店舗画像">
        </div>
            {% else %}
        </div>
        <img src="{{ detail.photo.pc.l }}" alt="店舗画像">
            {% endif %}
    </div>
</div>
{% endblock content %}

gsapp/templates/gourmet_list.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel = "stylesheet" href = "{%static 'css/gourmet_list.css'%}">
{% endblock head %}

{% block title %}モグマッチ｜店舗一覧{% endblock title %}

{% block logo %}
<a href="{% url 'gsapp:index' %}" class="logo-container">
    <img src="{% static 'images/logo_orange.svg' %}" alt="モグマッチ" id = "logo">
</a>
{% endblock logo %}

{% block content %}
<div class="background"></div>
<div class="content">
    <div class="results">
        <h2>検索結果</h2>
        <hr>
        {% if page_obj %}
            {% for shop in page_obj %}
            <a href="{% url 'gsapp:detail' shop.id %}" class="info">
                <div class="sentence">
                    <h2 class="name">{{ shop.name }}</h2>
                    <p class = "gray">{{ shop.address }}</p>
                </div>
                {% if is_mobile %}
                    <img src="{{ shop.photo.mobile.s }}" alt="画像" class="shop-img">
                {% else %}
                    <img src="{{ shop.photo.pc.m }}" alt="画像" class="shop-img">
                {% endif %}
            </a>
            <hr>
            {% endfor %}
            <nav class="pagination">
                <div class="nav-links">
                    <!-- {% if page_obj.has_previous %}
                        <a class="first page-numbers" href="{{ request.get_full_path }}&page=1">&laquo;</a>
                        <a class="prev page-numbers" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                    {% endif %} -->
        
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_num == page_obj.number %}
                            <span aria-current="page" class="page-numbers current">{{ page_num }}</span>
                        {% else %}
                            <a class="page-numbers" href="{{ request.get_full_path }}&page={{ page_num }}">{{ page_num }}</a>
                        {% endif %}
                    {% endfor %}
        
                    <!-- {% if page_obj.has_next %}
                        <a class="next page-numbers" href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        <a class="last page-numbers" href="{{ request.get_full_path }}&page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                    {% endif %} -->
                </div>
            </nav>
        {% else %}
            <p>ご希望のお店が周辺にありません。</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

gsapp/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link rel = "stylesheet" href = "{%static 'css/top.css'%}">
{% endblock head %}

{% block title %}モグマッチ｜トップ{% endblock title %}

{% block logo %}
<a href="{% url 'gsapp:index' %}" class="logo-container">
    <img src="{% static 'images/logo.svg' %}" alt="モグマッチ" id = "logo">
</a>{% endblock logo %}
{% block content %}

<div class="content">
    <div class="top">
        <div class="text-img-container">
            <img src="{% static 'images/top_text.svg' %}" alt="'モグマッチ'ってなに?">
        </div>
        <p class="white">簡単な質問に答えるだけで、周辺のお店を見つけることができる、新感覚のグルメ検索アプリ</p>
    </div>
    <div class="appeal">
        <p class="brown">３つの簡単な質問に答えて、あなたの近くのお店を見つけましょう！</p>
        <a href="{% url 'gsapp:search' %}" class="btn-top">お店を探す</a>
    </div>
    <div class="streaming-img">
        <div class="slides">
            {% for value in gourmet_photo %}
                {% if is_mobile %}
                    <img src="{{ value.photo.mobile.l }}" alt="画像" class="slide">
                {% else %}
                    <img src="{{ value.photo.pc.m }}" alt="画像" class="slide">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

gsapp/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link rel = "stylesheet" href = "{%static 'css/search.css'%}">
{% endblock head %}

{% block title %}モグマッチ｜検索{% endblock title %}

{% block logo %}
<a href="{% url 'gsapp:index' %}" class="logo-container">
    <img src="{% static 'images/logo.svg' %}" alt="モグマッチ" id = "logo">
</a>{% endblock logo %}

{% block content %}


<div id="food-img-container">
    <img src="{% static 'images/chinese_food.png' %}" alt="">
    <img src="{% static 'images/potato.png' %}" alt="">
    <img src="{% static 'images/italian.png' %}" alt="">
    <img src="{% static 'images/yakitori.png' %}" alt="">
</div>

<div id="genre" class = "content active">
    <p class = "bold" style = "color: white;">何を食べたいですか？</p>
    <div class="flex-btn-container">
        <a class = "btn btn-genre" href="">居酒屋</a>
        <a class = "btn btn-genre" href="">ダイニングバー・バル</a>
        <a class = "btn btn-genre" href="">創作料理</a>
        <a class = "btn btn-genre" href="">和食</a>
        <a class = "btn btn-genre" href="">洋食</a>
        <a class = "btn btn-genre" href="">中華</a>
        <a class = "btn btn-genre" href="">イタリアン・フレンチ</a>
        <a class = "btn btn-genre" href="">韓国料理</a>
        <a class = "btn btn-genre" href="">焼肉・ホルモン</a>
        <a class = "btn btn-genre" href="">アジア・エスニック料理</a>
        <a class = "btn btn-genre" href="">ラーメン</a>
        <a class = "btn btn-genre" href="">カフェ・スイーツ</a>
        <a class = "btn btn-genre" href="">こだわらない</a>
    </div>
    <button href="" class="btn next">次へ</button>
</div>
<div id="budget" class = "content">
    <p style="color:white;"class = "bold">予算はどれくらいですか？（2つまで選択可能）</p>
    <div class="flex-btn-container">
        <a class = "btn btn-budget" href="">〜500円</a>
        <a class = "btn btn-budget" href="">500〜1000円</a>
        <a class = "btn btn-budget" href="">1000〜1500円</a>
        <a class = "btn btn-budget" href="">1500〜2000円</a>
        <a class = "btn btn-budget" href="">2000〜3000円</a>
        <a class = "btn btn-budget" href="">3000〜4000円</a>
        <a class = "btn btn-budget" href="">4000〜5000円</a>
        <a class = "btn btn-budget" href="">5000〜7000円</a>
        <a class = "btn btn-budget" href="">7000〜10000円</a>
        <a class = "btn btn-budget" href="">10000〜15000円</a>
        <a class = "btn btn-budget" href="">15000〜20000円</a>
        <a class = "btn btn-budget" href="">20000〜30000円</a>
        <a class = "btn btn-budget" href="">30000円〜</a>
        <a class = "btn btn-budget" href="">こだわらない</a>
    </div>
    <button href="" class="btn next">次へ</button>
</div>
<div id="range" class = "content">
    <p style="color:white" class = "bold">現在地からの距離</p>

    <div id="slider-container">
        <input type="range" min="300" max="3000" value="1000" class="slider" id="myRange">
    </div>
    <button href="" id="search" class = "btn next">検索</button>
</div>

<div id="loading" class = "content">
    <div id="loading-spinner"></div>
</div>

{% endblock content %}

{% block js %}

<script type="text/javascript">

    //距離の変換
    function conversion_range(value){
        if(value<=300){
            range = "1";
        }else if(value>300 && value <= 500){
            range = "2";
        }else if(value>500 && value <= 1000){
            range = "3";
        }else if(value>1000 && value <= 2000){
            range = "4";
        }else if(value>2000 && value <= 3000){
            range = "5";
        }
        return range
    }

    //位置情報取得とurl作成後リダイレクト
    function get_location_and_redirect(genre_list, budget_list, range){
        if(navigator.geolocation){
            navigator.geolocation.getCurrentPosition(function(position){
                const lat = position.coords.latitude;
                const lng = position.coords.longitude;

                const genre_str = "genre=" + encodeURIComponent(genre_list.join(","));
                const budget_str = "&budget=" + encodeURIComponent(budget_list.join(","));
                const range_str = "&range=" + encodeURIComponent(range);
                const location_str = "&lat=" + encodeURIComponent(lat) + "&lng=" + encodeURIComponent(lng);

                const url = "/gourmet_list?" + genre_str + budget_str + range_str + location_str;
                window.location.href = url;

            },function(error){
                alert("位置情報を取得できませんでした。")
                window.location.href = "";
            });
        }else{
            window.location.href = "";
        }
    }

    //(m)→(km)
    function convert_km(value){
        const km = value / 1000;
        return km + "km";
    }

    // 徒歩の際のかかる時間の目安
    function convert_walking(meters){
        //平均的な歩行速度80m/min
        const speed = 80;
        walking_time = meters / speed;
        return Math.round(walking_time);

    }


    // --------スライダー-----------

    const slider = document.getElementById("myRange");
    const output = document.createElement("p");
    if(slider.value < 1000){
        output.textContent = slider.value + "m(徒歩" + convert_walking(slider.value) + "分)";
    }else{
        output.textContent = convert_km(slider.value) + "(徒歩" + convert_walking(slider.value) + "分)";
    }
    slider.oninput = function() {
        if(this.value < 1000){
            output.textContent = this.value + "m(徒歩" + convert_walking(this.value) + "分)";
        }else{
            output.textContent = convert_km(this.value) + "(徒歩" + convert_walking(this.value) + "分)";
        }
    };
    document.getElementById("slider-container").appendChild(output);

    //-----------------------------

    btn_list = [
        document.getElementsByClassName("btn-genre"), //ジャンル
        document.getElementsByClassName("btn-budget"), //予算
    ]
    genre = {
        "居酒屋": "G001",
        "ダイニングバー・バル": "G002",
        "創作料理": "G003",
        "和食": "G004",
        "洋食": "G005",
        "イタリアン・フレンチ": "G006",
        "中華": "G007",
        "焼肉・ホルモン": "G008",
        "アジア・エスニック料理": "G009",
        "ラーメン": "G013",
        "カフェ・スイーツ": "G014",
        "韓国料理": "G017",
        "こだわらない": "",
    };
    
    budget = {
        "〜500円": "B009",
        "500〜1000円": "B010",
        "1000〜1500円": "B011",
        "1500〜2000円": "B001",
        "2000〜3000円": "B002",
        "3000〜4000円": "B003",
        "4000〜5000円": "B008",
        "5000〜7000円": "B004",
        "7000〜10000円": "B005",
        "10000〜15000円": "B006",
        "15000〜20000円": "B012",
        "20000〜30000円": "B013",
        "30000円〜": "B014",
        "こだわらない": "",
    };
    

    //btnのactive, deactive処理
    for(let i = 0; i < btn_list.length; i ++){ //2回
        for(let j = 0; j < btn_list[i].length; j ++){
            btn_list[i][j].addEventListener("click", e => {
                e.preventDefault();
                let activeButtons = document.querySelectorAll('.btn-budget.active');
                if(btn_list[i][j].classList.contains("active") == true){
                    btn_list[i][j].classList.remove("active");
                }else if(activeButtons.length < 2){
                    btn_list[i][j].classList.add("active");
                }
            });
        }
    }

    // 画面の遷移
    const contents = document.getElementsByClassName("content") //0:genre, 1:budget, 2:range
    const btn_next = document.getElementsByClassName("next");
    const btn_search = document.getElementById("search");

    var state = 0;

    var genre_list = [];
    var budget_list = [];

    //「次へ」ボタンの処理
    for(i = 0; i < btn_next.length; i ++){
        btn_next[i].addEventListener("click", e => {
            e.preventDefault();
            contents[state].classList.remove("active");
            state += 1;
            contents[state].classList.add("active");
        });
    };

    // 「検索」ボタン処理
    btn_search.addEventListener("click", e => {
        for(let i = 0; i < btn_list.length; i ++){
            for(let j = 0; j < btn_list[i].length; j ++){
                if(btn_list[i][j].classList.contains("active") == true){
                    if(i == 0){ //genre
                        let genreName = btn_list[i][j].textContent;
                        genre_list.push(genre[genreName]);
                    }else{ //budget
                        let budgetName = btn_list[i][j].textContent;
                        budget_list.push(budget[budgetName]);
                    }
                }
            }
        }
        var range = conversion_range(slider.value);
        get_location_and_redirect(genre_list, budget_list, range)
    })

</script>

{% endblock js %}